# Every night at 00:00UTC
# Download the latest master branch build of windows testing bundle
# and run it.
# After that passes, hand over to the Buildkite nightly pipeline.

name: cardano-wallet Windows Tests

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  tests:
    runs-on: windows-2016
    name: Run tests on Windows
    steps:
      - name: Fetch Windows testing bundle
        shell: powershell
        run: |
          $url = "https://hydra.iohk.io/job/Cardano/cardano-wallet/cardano-wallet-tests-win64/latest/download/1"
          $output = "cardano-wallet-tests-win64.zip"
          Invoke-WebRequest -Uri $url -OutFile $output
          Expand-Archive -LiteralPath $output -DestinationPath .
          Get-ChildItem
      - name: 'cardano-wallet-core:unit'
        run: '.\\cardano-wallet-core-test-unit.exe --color'
      - name: 'cardano-wallet:unit'
        run: '.\\cardano-wallet-test-unit.exe --color'
      - name: 'cardano-wallet-cli:unit'
        run: '.\\cardano-wallet-cli-test-unit.exe --color'
      - name: 'text-class:unit'
        run: '.\\text-class-test-unit.exe --color'
      - name: 'cardano-wallet-launcher:unit'
        run: '.\\cardano-wallet-launcher-test-unit.exe --color'
        continue-on-error: true
      - name: 'cardano-wallet:integration'
        run: '.\\cardano-wallet-test-integration.exe --color'
        timeout-minutes: 60
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: "Advance windows-tests-pass and all-tests-pass branches"
        shell: bash
        run: "bash .buildkite/push-branch.sh windows-tests-pass linux-tests-pass all-tests-pass"
        env:
          ACTIONS_SSH_KEY: "${{ secrets.ACTIONS_SSH_KEY }}"
