name: E2E Linux

on:
  schedule:
  - cron:  "0 20 * * *"
  workflow_dispatch:
    inputs:
      network:
        description: 'Network'
        required: true
        default: 'preview'
      node_db_cache:
        description: 'Node DB Cache'
        required: true
        default: 'GH'
        type: choice
        options:
        - AWS
        - GH
      pr:
        description: 'PR number or "master"'
        default: 'master'
      tags:
        description: 'Test tags (all, light, offchain...)'
        default: 'all'

defaults:
  run:
    working-directory: ./test/e2e

env:
  nix_config: |
    access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
    substituters = https://cache.nixos.org/ https://cache.iog.io
    trusted-public-keys = hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=
    allow-dirty = true
  nix_version: "2.11.1"
  cachix_name: adp

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: 'ğŸ“¥ Checkout repository'
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: 'â„ Install Nix'
      uses: cachix/install-nix-action@v18
      with:
        install_url: "https://releases.nixos.org/nix/nix-${{ env.nix_version }}/install"
        extra_nix_config: ${{ env.nix_config }}

    - uses: cachix/cachix-action@v10
      with:
        name: ${{ env.cachix_name }}
        authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

    - name: 'â„ Run command inside a nix shell'
      run: |
        nix develop --command cabal update
        nix develop --command cardano-node --version

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.1.2
        bundler-cache: true

    - name: Install dependencies
      run: bundle install

    - name: ğŸ•’ Get Date/Time
      id: date-time
      shell: bash
      run: |
        echo "value=$(rake datetime)" >> $GITHUB_OUTPUT

    - name: ğŸ’½ AWS Cache node db
      if: ${{ env.NODE_DB_CACHE == 'AWS' }}
      run: rake get_latest_node_db[$NETWORK]

    - name: ğŸ’¾ GH Cache node db
      if: ${{ env.NODE_DB_CACHE == 'GH' }}
      id: cache
      uses: actions/cache@v2.1.7
      with:
        path: test/e2e/state/node_db/${{ env.NETWORK }}
        key: node-db-${{ runner.os }}-${{ env.NETWORK }}-${{ steps.date-time.outputs.value }}
        restore-keys: |
          node-db-${{ runner.os }}-${{ env.NETWORK }}-

    - name: ğŸ’¾ Cache wallet db
      id: cache-wallet
      uses: actions/cache@v2.1.7
      with:
        path: test/e2e/state/wallet_db/${{ env.NETWORK }}
        key: wallet-db3-${{ runner.os }}-${{ env.NETWORK }}-${{ steps.date-time.outputs.value }}
        restore-keys: |
          wallet-db3-${{ runner.os }}-${{ env.NETWORK }}-

    - name: âš™ï¸ Setup (get latest bins and configs and decode fixtures)
      run: rake setup[$NETWORK,$PR]

    - name: ğŸ” Display versions
      run: rake display_versions

    - name: ğŸš€ Start node and wallet
      run: rake start_node_and_wallet[$NETWORK]

    - name: â³ Wait until node is synced
      run: rake wait_until_node_synced

    - name: ğŸ§ª Run all tests
      run: rake spec SPEC_OPTS="-t $TAGS"

    - name: ğŸ Stop node and wallet
      run: rake stop_node_and_wallet[$NETWORK]

    - name: ğŸ“ Upload state
      uses: actions/upload-artifact@v2
      if: always()
      with:
        name: ${{ runner.os }}-state
        path: |
          test/e2e/state/logs
          test/e2e/state/configs
          test/e2e/state/wallet_db

    env:
      TESTS_E2E_FIXTURES: ${{ secrets.TESTS_E2E_FIXTURES }}
      NETWORK: ${{ github.event.inputs.network || 'preprod' }}
      PR: ${{ github.event.inputs.pr || '' }}
      NODE_DB_CACHE: ${{ github.event.inputs.node_db_cache || 'GH' }}
      TAGS: ${{ github.event.inputs.tags || 'all' }}
