name: Linux E2E Tests

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: "Build E2E dependencies"
    runs-on: [self-hosted, linux, x86_64, cardano-wallet]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Build derivations
        run: nix build --quiet .#cardano-node .#cardano-wallet .#e2e

  e2e:
    name: "Run E2E Tests"
    needs: build
    runs-on: [self-hosted, linux, x86_64, cardano-wallet]
    timeout-minutes: 240
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run E2E tests
        env:
          HAL_E2E_PREPROD_MNEMONICS: ${{ secrets.HAL_E2E_PREPROD_MNEMONICS }}
        run: nix shell --quiet .#cardano-node .#cardano-wallet .#e2e 'nixpkgs#gnutar' 'nixpkgs#p7zip' -c e2e

      - name: Cleanup temp directories
        if: always()
        run: rm -rf /tmp/e2e-* /tmp/test-cluster*
