name: Linux E2E Tests

on:
  workflow_dispatch:

jobs:
  build:
    name: "Build E2E dependencies"
    runs-on: [self-hosted, linux, x86_64, cardano-wallet]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Build derivations
        run: nix build -L .#cardano-node .#cardano-wallet .#e2e

  e2e:
    name: "Run E2E Tests"
    needs: build
    runs-on: [self-hosted, linux, x86_64, cardano-wallet]
    timeout-minutes: 120
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run E2E tests
        run: nix shell .#cardano-node .#cardano-wallet .#e2e 'nixpkgs#gnutar' 'nixpkgs#p7zip' -c e2e
