name: macOS Artifacts

on:
  push:
    branches: [master]
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-integration:
    name: "Build Integration Tests (macOS, arm64)"
    runs-on: [self-hosted, macOS, ARM64, cardano-wallet]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build integration test executable
        run: nix build -L .#packages.aarch64-darwin.integration-exe

  package-intel:
    name: "Build Package (macOS, x86_64)"
    runs-on: [self-hosted, macOS, ARM64, cardano-wallet]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build macOS Intel package
        run: nix build -L -o result/macos-intel .#packages.x86_64-darwin.ci.artifacts.macos-intel.release

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: macos-intel-package
          path: result/macos-intel/

  package-silicon:
    name: "Build Package (macOS, arm64)"
    runs-on: [self-hosted, macOS, ARM64, cardano-wallet]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build macOS Silicon package
        run: nix build -L -o result/macos-silicon .#packages.aarch64-darwin.ci.artifacts.macos-silicon.release

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: macos-silicon-package
          path: result/macos-silicon/
