name: macOS Integration Tests

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: "Build integration dependencies (macOS)"
    runs-on: [self-hosted, macOS, ARM64, cardano-wallet]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Build derivations
        run: >-
          nix build --quiet
          .#cardano-node .#cardano-cli
          .#cardano-wallet .#local-cluster
          .#packages.aarch64-darwin.integration-exe

  integration:
    name: "Conway Integration Tests (macOS)"
    needs: build
    runs-on: [self-hosted, macOS, ARM64, cardano-wallet]
    timeout-minutes: 120
    env:
      LOCAL_CLUSTER_CONFIGS: lib/local-cluster/test/data/cluster-configs
      LOCAL_CLUSTER_ERA: conway
      CARDANO_WALLET_TEST_DATA: lib/integration/test/data
      TESTS_RETRY_FAILED: 1
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run integration tests
        run: |
          mkdir -p integration-test-dir/cluster.logs
          export CLUSTER_LOGS_DIR_PATH=integration-test-dir/cluster.logs
          export INTEGRATION_TEST_DIR=integration-test-dir
          nix shell --quiet .#cardano-node .#cardano-cli -c \
            nix shell --quiet .#cardano-wallet .#local-cluster .#packages.aarch64-darwin.integration-exe \
              -c integration-exe -j6

      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: macos-integration-test-logs
          path: integration-test-dir/
