name: macOS Integration Tests

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: "Build integration test dependencies"
    runs-on: [self-hosted, macOS, ARM64, cardano-wallet]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Build derivations
        run: nix build -L .#cardano-wallet .#local-cluster .#integration-exe .#cardano-node .#cardano-cli

  conway-integration:
    name: "Conway Integration Tests (macOS)"
    needs: build
    runs-on: [self-hosted, macOS, ARM64, cardano-wallet]
    timeout-minutes: 120
    env:
      LOCAL_CLUSTER_CONFIGS: lib/local-cluster/test/data/cluster-configs
      LOCAL_CLUSTER_ERA: conway
      CARDANO_WALLET_TEST_DATA: lib/integration/test/data
      TESTS_RETRY_FAILED: 1
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run integration tests
        run: |
          mkdir -p integration-test-dir/cluster.logs
          export CLUSTER_LOGS_DIR_PATH=integration-test-dir/cluster.logs
          export INTEGRATION_TEST_DIR=integration-test-dir
          nix shell 'nixpkgs#just' -c just conway-integration-tests 2

      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: macos-integration-test-logs
          path: integration-test-dir/
