name: macOS Nix Check

on:
  push:
    branches: [master]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check-nix:
    name: "Check Nix (macOS)"
    runs-on: [self-hosted, macOS, ARM64, cardano-wallet]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check nix version
        run: nix --version

      - name: Check flake info
        run: nix flake info

  attic-cache:
    name: "Dev Shell Attic Cache (macOS)"
    needs: check-nix
    runs-on: [self-hosted, macOS, ARM64, cardano-wallet]
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push dev shell to Attic
        env:
          ATTIC_TOKEN: ${{ secrets.ATTIC_TOKEN }}
          system: aarch64-darwin
        run: nix develop path:./scripts/buildkite/main -c ./scripts/buildkite/main/attic-cache.sh
