name: Publish Docs

on:
  push:
    branches:
      - master
    tags:
      - 'v*'
  pull_request:

env:
  PR_NUMBER: ${{ github.event.pull_request.number }}
  nix_config: |
    access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
    substituters = https://hydra.iohk.io https://cache.nixos.org/
    trusted-public-keys = hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=
    allow-dirty = true
  nix_version: "2.6.0"
  cachix_name: adp

jobs:
  docs:
    runs-on: ubuntu-20.04
    env:
      PUBLISH_DIR: _build
    steps:
      - name: 'ðŸ“¥ Checkout repository'
        uses: actions/checkout@v2

      - name: 'â„ Install Nix'
        uses: cachix/install-nix-action@v16
        with:
          install_url: "https://releases.nixos.org/nix/nix-${{ env.nix_version }}/install"
          extra_nix_config: ${{ env.nix_config }}

      - uses: cachix/cachix-action@v10
        with:
          name: ${{ env.cachix_name }}
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - name: 'ðŸ”§ Set versions'
        id: versions
        run: |
          if [[ $GITHUB_REF =~ ^refs/tags/v ]]; then
            tag="${GITHUB_REF/refs\/tags\//}"
            commit_message="Release $tag"
          else
            tag=""
            commit_message="$default_commit_message"
          fi
          echo "::set-output name=commit_message::$commit_message"
          echo "::set-output name=tag::$tag"
        env:
          default_commit_message: |
            docs: ${{ github.event.head_commit.message }}

            Source commit: ${{ github.sha }}

      - name: 'â„ Install dependencies'
        run: |
          develop_env="$GITHUB_WORKSPACE/develop.env"
          nix develop .#docs --ignore-environment --command env > "$develop_env"
          echo "develop_env=$develop_env" >> $GITHUB_ENV

      - name: 'ðŸ“¸ Build Documentation'
        run: |
          build_dir="$PUBLISH_DIR"
          if [ -n "$PR_NUMBER" ]; then
            build_dir="$build_dir/_pr/$PR_NUMBER"
            nix develop .#docs -c yq --in-place -y '.template.baseUrl|=.+"_pr/\(env.PR_NUMBER)/"' docs/.deploy/github/index.yaml
          fi
          echo "build_dir=$build_dir" >> $GITHUB_ENV

          mkdir -p "$build_dir"
          nix develop .#docs -c emanote --layers "docs;docs/.deploy/github" gen "$build_dir"
          ./scripts/gh/update-docs.sh "$build_dir" ${{ steps.versions.outputs.tag }}

      - name: 'TODO list'
        run: |
          nix develop .#docs --command ./scripts/todo-list.sh | tee "$build_dir"/TODO

      - name: 'ðŸ“˜ Publish'
        if: ${{ github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/v') }}
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.WILLIAM_KING_TOKEN }}
          enable_jekyll: false
          publish_dir: ${{ env.PUBLISH_DIR }}
          keep_files: true
          user_name: 'William King Noel Bot'
          user_email: 'adrestia@iohk.io'
          full_commit_message: ${{ steps.versions.outputs.commit_message }}
