name: Rubocop

on:
  push:
    branches: [ "master" ]
    paths: ['test/e2e/**.rb']
  pull_request:
    branches: [ "master" ]
    paths: ['test/e2e/**.rb']

permissions:
  contents: read

defaults:
  run:
    working-directory: ./test/e2e

jobs:
  rubocop-linter:
    runs-on: ubuntu-latest

    steps:
    - name: ğŸ“¥ Checkout repository
      uses: actions/checkout@v3.2.0

    - name: ğŸ’ Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.1.2
        bundler-cache: true

    - name: ğŸ‘® Rubocop
      run: |
        gem install rubocop
        rubocop
